apply plugin: 'fabric-loom'

// Minecraft 1.19 requires Java 17
configureJavaVersion(17)

dependencies {
    // Common module
    implementation project(':common')

    minecraft 'com.mojang:minecraft:1.19.2'
    mappings "net.fabricmc:yarn:1.19.2+build.28:v2"
    modImplementation "net.fabricmc:fabric-loader:0.18.2"
    modImplementation "net.fabricmc.fabric-api:fabric-api:0.139.5+"
}

processResources {
    inputs.property "version", project.version
    
    filesMatching("fabric.mod.json") {
        expand "version": project.version
    }
}

jar {
    from(project(':common').sourceSets.main.output)
    from("LICENSE") {
        rename { "${it}_${project.archivesBaseName}" }
    }
}
